# Generated by Django 3.0.7 on 2020-06-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('is_spicy', models.BooleanField()),
                ('is_vegan', models.BooleanField()),
                ('is_glutenfree', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('opening_hours', models.CharField(max_length=20)),
                ('min_order_amount', models.PositiveIntegerField()),
                ('cuisines', models.ManyToManyField(to='restaurants.Cuisine')),
                ('menu', models.ManyToManyField(to='restaurants.Course')),
            ],
        ),
    ]
