# Generated by Django 3.0.7 on 2020-07-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(blank=True, to='restaurants.Course'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='min_order_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
